//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Resources.UserProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserProfileResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfileResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contract.Resources.UserProfile.UserProfileResource", typeof(UserProfileResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUser_User_Email_Invalid.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUser_User_Email_Invalid {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUser_User_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUser_User_Empty.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUser_User_Empty {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUser_User_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUser_User_Username_Invalid.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUser_User_Username_Invalid {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUser_User_Username_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUserPassword_Password_CurrentPassword_Invalid.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUserPassword_Password_CurrentPassword_Invalid {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUserPassword_Password_CurrentPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUserPassword_Password_Empty.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUserPassword_Password_Empty {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUserPassword_Password_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUserPassword_Password_NewPassword_Invalid.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUserPassword_Password_NewPassword_Invalid {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUserPassword_Password_NewPassword_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUserPassword_Password_NewPassword_NotEqual.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUserPassword_Password_NewPassword_NotEqual {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUserPassword_Password_NewPassword_NotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile_Commands_UpdateProfileUserPassword_Password_RepeatNewPassword_Invalid.
        /// </summary>
        public static string Profile_Commands_UpdateProfileUserPassword_Password_RepeatNewPassword_Invalid {
            get {
                return ResourceManager.GetString("Profile_Commands_UpdateProfileUserPassword_Password_RepeatNewPassword_Invalid", resourceCulture);
            }
        }
    }
}
