//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Contract.Resources.Account {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AccountResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AccountResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Contract.Resources.Account.AccountResource", typeof(AccountResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha_CaptchaCode_Empty.
        /// </summary>
        public static string Captcha_CaptchaCode_Empty {
            get {
                return ResourceManager.GetString("Captcha_CaptchaCode_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha_CaptchaCode_Invalid.
        /// </summary>
        public static string Captcha_CaptchaCode_Invalid {
            get {
                return ResourceManager.GetString("Captcha_CaptchaCode_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captcha_Empty.
        /// </summary>
        public static string Captcha_Empty {
            get {
                return ResourceManager.GetString("Captcha_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or Password is incorect.
        /// </summary>
        public static string User_Queries_SignIn_Invalid_Username_Password {
            get {
                return ResourceManager.GetString("User_Queries_SignIn_Invalid_Username_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignIn_User_Empty.
        /// </summary>
        public static string User_Queries_SignIn_User_Empty {
            get {
                return ResourceManager.GetString("User_Queries_SignIn_User_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignIn_User_Password_Invalid.
        /// </summary>
        public static string User_Queries_SignIn_User_Password_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignIn_User_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignIn_User_Username_Invalid.
        /// </summary>
        public static string User_Queries_SignIn_User_Username_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignIn_User_Username_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exist.
        /// </summary>
        public static string User_Queries_Signup_Exist_Email {
            get {
                return ResourceManager.GetString("User_Queries_Signup_Exist_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Exist.
        /// </summary>
        public static string User_Queries_Signup_Exist_Mobile {
            get {
                return ResourceManager.GetString("User_Queries_Signup_Exist_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Exist.
        /// </summary>
        public static string User_Queries_Signup_Exist_Username {
            get {
                return ResourceManager.GetString("User_Queries_Signup_Exist_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_Email_Invalid.
        /// </summary>
        public static string User_Queries_SignUp_User_Email_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_Email_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_Empty.
        /// </summary>
        public static string User_Queries_SignUp_User_Empty {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_FirstName_Empty.
        /// </summary>
        public static string User_Queries_SignUp_User_FirstName_Empty {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_FirstName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_FirstName_Invalid.
        /// </summary>
        public static string User_Queries_SignUp_User_FirstName_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_FirstName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_LastName_Empty.
        /// </summary>
        public static string User_Queries_SignUp_User_LastName_Empty {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_LastName_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_LastName_Invalid.
        /// </summary>
        public static string User_Queries_SignUp_User_LastName_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_LastName_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_Mobile_Invalid.
        /// </summary>
        public static string User_Queries_SignUp_User_Mobile_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_Mobile_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_Password_Invalid.
        /// </summary>
        public static string User_Queries_SignUp_User_Password_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_Password_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User_Queries_SignUp_User_Username_Invalid.
        /// </summary>
        public static string User_Queries_SignUp_User_Username_Invalid {
            get {
                return ResourceManager.GetString("User_Queries_SignUp_User_Username_Invalid", resourceCulture);
            }
        }
    }
}
